_description: |
  A simple subheader component.

text:
  _label: Subheader Text
  _placeholder:
    height: 20px
    text: Subheader Text
  _has:
    input: inline
    buttons:
      - link
      - italic
      - underline
    validate:
      required: true
