_description: |
  Dynamic stations list

filterBy:
  _label: filter stations by
  _has:
    input: radio
    options:
      - recent
      - local
      - market
      - genre
    validate:
      required: true

listTitle:
  _label: Title of stations list
  _has:
    validate:
      required: true
