_description: |
  A component used to indicate the legal contest description and activation window on a contest page.

contestHeadline:
  _subscribe: contestHeadline

contestStartDate:
  _subscribe: contestStartDate

contestEndDate:
  _subscribe: contestEndDate

contestSlug:
  _subscribe: contestSlug

contestDateRange:
  _subscribe: contestDateRange

rulesBodyText:
  _label: Contest Rules
  _placeholder:
    height: 200px
    text: New Contest Rules Body Text
    required: true
  _has:
    input: inline
    type: multi-line
    buttons:
      - bold
      - italic
      - strike
      - link
