_version: 5.0
_description: |
  Latest videos module

excludeSubscriptions:
  _label: Exclude Subscriptions
  _has:
    input: checkbox

items:
  _label: Latest Videos
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 6
    props:
    -
      prop: url
      _label: URL (page containing video in lede component)
      _has:
        input: content-search
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80

sectionFront:
  _label: Section Front
  _subscribe: sectionFront

filterTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: filterTag
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

filterSecondarySectionFronts:
  _label: Exclude Secondary Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: secondary-section-fronts

title:
  _label: Video Section Title
  _has:
    input: text

primaryContentLabel:
  _label: Label above the primary item
  _has:
    input: text
    validate:
      max: 30

_groups:
  settings:
    fields:
      - title
      - primaryContentLabel
      - filterTags
      - filterSecondarySectionFronts
      - excludeSubscriptions

