_version: 1.0
_description: |
  Latest videos module

items:
  _label: Latest Videos
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 6
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

filterTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: filterTag
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

filterSecondaryArticleTypes:
  _label: Exclude Secondary Article Types
  _has:
    input: checkbox-group
    options:
      - Pop
      - Alternative
      - Country
      -
        name: Hip-Hop R&B
        value: Hip-Hop R&B
      - Rock
      - Icons
      - Entertainment News
      - Movies
      - Television
      - National News
      - Politics
      - Local Politics
      - Small Business Pulse
      - NFL
      - MLB
      - NBA
      - NHL
      - NCAA Football
      - NCAA Basketball
      -
        name: MMA & WWE
        value: MMA & WWE

_groups:
  settings:
    fields:
      - filterTags
      - filterSecondaryArticleTypes
