_confirmRemoval: true

includePodcastModule:
  _label: Include podcast module on page?
  _has: checkbox

podcastList:
  _component:
    include:
      - podcast-list

twoColumnComponent:
  _component:
    include:
      - two-column-component

stationsCarousel:
  _placeholder:
    text: Stations Carousel
    height: 300px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - stations-carousel

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

# Component properties
sectionLead:
  _component:
    include:
    - section-lead

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager

_groups:
  settings:
    fields:
      - includePodcastModule
