_confirmRemoval: true

titleLocked:
  _label: Is title locked?
  _has: checkbox

stationSlug:
  _label: Station Slug
  _publish:
    - sectionFront
    - ogTitle
    - pageListTitle
    - pageTitle
  _has:
    input: text
    validate:
      required: true

includePodcastModule:
  _label: Include podcast module on page?
  _has: checkbox

podcastList:
  _component:
    include:
      - podcast-list

twoColumnComponent:
  _component:
    include:
      - two-column-component

stationsCarousel:
  _placeholder:
    text: Stations Carousel
    height: 300px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - stations-carousel

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

# Component properties
sectionLead:
  _component:
    include:
    - section-lead

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager

_groups:
  settings:
    fields:
      - stationName
      - stationCallsign
      - stationSlug
      - includePodcastModule

stationName:
  _publish: stationName
  _label: Station Name
  _has: static
  _reveal:
    field: stationName
    operator: truthy

stationCallsign:
  _publish: stationCallsign
  _label: Station Callsign
  _has: static
  _reveal:
    field: stationCallsign
    operator: truthy
