_description: |
  Embeds a tweet via the tweet’s URL.

url:
  _label: URL
  _has:
    input: text
    type: url
    help: https://twitter.com/username/status/ID

showThread:
  _label: Show Thread
  _has: checkbox

showMedia:
  _label: Show Media
  _has: checkbox

_groups:
  default:
    fields:
      - url
      - showThread
      - showMedia
    _placeholder:
      height: 50px
      text: Tweet
      ifEmpty: url
