_description: |
  A header for the author page

_confirmRemoval: true

author:
  _label: Author Name
  _has:
    input: select-list
    list: authors
    validate:
      required: true

profileImage:
  _label: Image URL
  _has:
    input: advanced-image-upload
    webLabel: Insert Image via Web
    webHelp: Supply a valid HTTPS url to an image file then click "done" button
    uploadLabel: Upload Image Attachment
    uploadHelp: Choose an image file from your computer

scheduleTime:
  _label: Schedule Time
  _has:
    input: text

bio:
  _label: Biography
  _has:
    input: text

facebookHandle:
  _label: Facebook Handle
  _has:
    input: text

twitterHandle:
  _label: Twitter Handle
  _has:
    input: text

youtubeHandle:
  _label: YouTube Account
  _has:
    input: text

instagramHandle:
  _label: Instagram Handle
  _has:
    input: text

email:
  _label: email
  _has:
    input: text

_groups:
  settings:
    fields:
      - author
      - profileImage
      - scheduleTime
      - bio
      - facebookHandle
      - twitterHandle
      - youtubeHandle
      - instagramHandle
      - email
    _placeholder:
      height: 250px
      text: Author Header
      ifEmpty: author
