_description: |
  A header for the author page

_confirmRemoval: true

author:
  _label: Author/Host Name
  _has:
    input: select-list
    list: authors
    validate:
      required: true

profileImage:
  _label: Image URL
  _has:
    input: advanced-image-upload
    webLabel: Insert Image via Web
    webHelp: Supply a valid HTTPS url to an image file then click "done" button
    uploadLabel: Upload Image Attachment
    uploadHelp: Choose an image file from your computer

scheduleTime:
  _label: Schedule Time
  _has:
    input: text
    help: Enter the weekday(s) and time(s) of the Host’s On Air Schedule

bio:
  _label: Biography
  _has:
    input: text
    help: Enter the Author or Host’s professional biography

facebook:
  _label: Facebook Handle
  _has:
    input: text
    help: "Link to the Author or Host’s Facebook Account (for example: facebook.com/NAMEHERE)"

twitter:
  _label: Twitter Handle
  _has:
    input: text
    help: "Link to the Author or Host’s Twitter Account (for example: twitter.com/NAMEHERE)"

youtube:
  _label: YouTube Account
  _has:
    input: text
    help: "Link to the Author or Host’s YouTube Account (for example: youtube.com/channel/NAMEHERE)"

instagram:
  _label: Instagram Handle
  _has:
    input: text
    help: "Link to the Author or Host’s Instagram Account (for example: instagram.com/NAMEHERE)"

email:
  _label: Email
  _has:
    input: text
    help: Enter the Author or Host’s public-facing email address

_groups:
  settings:
    fields:
      - author
      - profileImage
      - scheduleTime
      - bio
      - facebook
      - twitter
      - youtube
      - instagram
      - email
    _label: Author/Host Header Settings
    _placeholder:
      height: 250px
      text: Author/Host Header
      ifEmpty: author
