_description: |
  A header for the author page

_confirmRemoval: true

author:
  _label: Author Name
  _has:
    input: select-list
    list: authors
    validate:
      required: true

profileImage:
  _label: Image URL
  _has:
    input: advanced-image-upload
    webLabel: Insert Image via Web
    webHelp: Supply a valid HTTPS url to an image file then click "done" button
    uploadLabel: Upload Image Attachment
    uploadHelp: Choose an image file from your computer

scheduleTime:
  _label: Schedule Time
  _has:
    input: text


socialButtonsShow:
  _label: Add Social Media
  _has:
    validate:
      required: true
    input: checkbox

socialButtonsURLs:
  _label: Add Social Button
  _has:
    input: complex-list
    props:
      -
        prop: type
        _label: Social Type
        _has:
          input: radio
          options:
            - facebook
            - twitter
            - instagram
            - youtube
            - email
      -
        prop: url
        _label: Social Page URL
        _has:
          input: text
          type: url
  _reveal:
    field: socialButtonsShow
    operator: ===
    value: true

bio:
  _label: Biography
  _has:
    input: text

_groups:
  settings:
    fields:
      - author
      - profileImage
      - scheduleTime
      - bio
      - socialButtonsShow
      - socialButtonsURLs
    _placeholder:
      height: 250px
      text: Author Header
      ifEmpty: author
