_version: 2.0
_description: |
  Receives an image and renders it in the head

defaultImageUrl:
  _subscribe:
    - pageMetaImage
    - feedImgUrl

imageUrl:
  _label: Image Url
  _has:
    input: default-text-with-override
    type: url
    defaultField: defaultImageUrl
    permissionToOverride:
      update: meta-tags
    help: This value will be the page's meta image or content's feed image.

_groups:
  settings:
    _label: Meta Image
    fields:
      - imageUrl
