_version: 1.0
_description: |
  Receives an image and renders it in the head

_permission:
  update: section-fronts_meta-tags

imageUrl:
  _label: Image Url
  _display: settings
  _subscribe:
    - pageMetaImage
    - feedImgUrl
  _has:
    -
      fn: text
      type: url
    - label
    -
      fn: description
      value: URL of an image to show in the feeds. Usually the first image in an article.
