_version: 2.0
_description: |
  Receives an image and renders it in the head

imageUrl:
  _label: Image Url
  _subscribe:
    - pageMetaImage
    - feedImgUrl
  _has:
    input: text
    type: url
    help: URL of an image to show in the feeds. Usually the first image in an article.

_groups:
  settings:
    _label: Meta Image
    fields:
      - imageUrl
