_description: |
  A group of redirect URL patterns to force a page to redirect to a different url

redirects:
  _label: Redirect URL collection
  _placeholder:
    height: 100px
    text: Add Redirects
  _has:
    input: complex-list
    filter: true
    props:
    -
      prop: url
      _label: URL pattern
      _has:
        input: text
        type: url
        help: Use * as a wildcard match
        validate:
          required: true
    -
      prop: redirect
      _label: Redirect
      _has:
        input: text
        type: url
        validate:
          required: true

_groups:
  redirects:
    _label: Redirects

    fields:
    - redirects
