_description: |
  Creates a stats standings component

sport:
  _label: Sport
  _has:
    input: select
    validate:
      required: true


league:
  _label: League
  _has:
    input: select
    validate:
      required: true

teamId:
  _label: Team ID
  _has:
    input: text
    validate:
      required: true

_groups:
  settings:
    _label: stats-standings
    _placeholder:
      text: stats-standings
      height: 30px
      ifEmpty: sport or league or teamId
    fields:
      - sport
      - league
      - teamId
        