_description: |
  Global footer

_confirmRemoval: true
_permission:
  update: footer

socialButtonsShow:
  _label: Show social buttons?
  _has:
    validate:
      required: true
    input: checkbox
    help: By default, social buttons are added to footer. Uncheck to remove.

socialButtonsURLs:
  _label: Add Social Button
  _has:
    input: complex-list
    props:
      -
        prop: type
        _label: Social Type
        _has:
          validate:
            required: true
          input: radio
          options:
            - facebook
            - twitter
            - instagram
            - youtube
      -
        prop: url
        _label: Social Page URL
        _has:
          validate:
            required: true
          input: text
          type: url
  _reveal:
    field: socialButtonsShow
    operator: ===
    value: true

appBadgesShow:
  _label: Show app download badges?
  _has:
    validate:
      required: true
    input: checkbox
    help: By default, app badges are added to footer. Uncheck to remove.

appBadgesURLs:
  _label: App Badges
  _has:
    input: complex-list
    props:
      -
        prop: type
        _label: Badge Type
        _has:
          validate:
            required: true
          input: radio
          options:
            -
              name: app store
              value: app-store
            -
              name: google play
              value: google-play
      -
        prop: url
        _label: Badge URL
        _has:
          validate:
            required: true
          input: text
          type: url
  _reveal:
    field: appBadgesShow
    operator: ===
    value: true

links:
  _label: Footer Links
  _has:
    input: complex-list
    validate:
      required: false
    props:
      -
        prop: text
        _label: Category Label
        _has:
          input: text
          enforceMaxlength: true
          validate:
            required: true
            max: 40
            maxMessage: This field must be 40 or fewer characters long
      -
        prop: list
        _label: Category's Links
        _has:
          input: complex-list
          validate:
            required: false
          props:
            -
              prop: text
              _label: Link Text
              _has:
                input: text
                enforceMaxlength: true
                validate:
                  required: true
                  max: 40
                  maxMessage: This field must be 40 or fewer characters long
            -
              prop: url
              _label: Link Url
              _has:
                input: text
                type: url
                validate:
                  required: true
            -
              prop: newtab
              _label: Open in new tab
              _has:
                input: checkbox

_groups:
  settings:
    fields:
      - socialButtonsShow (Social Buttons)
      - socialButtonsURLs (Social Buttons)
      - appBadgesShow (App Badges)
      - appBadgesURLs (App Badges)
      - links (Links)
