_version: 2.0
_description: |
  Adds `<link rel="canonical">`, `article:published_time`, and `og:url` tags to the head.

  If an article is syndicated, the canonical link will point to the url of the original article.

defaultSyndicatedUrl:
  _subscribe: syndicatedUrl

defaultDate:
  _subscribe: publishDate

url:
  _label: Canonical URL
  _has:
    input: default-text-with-override
    type: url
    # defaultUrl is set during model.save
    defaultField: defaultUrl
    permissionToOverride:
      update: meta-tags
    help: URL of the current page. For articles, this is the canonical url.

syndicatedUrl:
  _label: Syndicated Url
  _has:
    input: default-text-with-override
    type: url
    defaultField: defaultSyndicatedUrl
    permissionToOverride:
      update: meta-tags
    help: >-
      For articles, this is set if you specify syndication in the article
      settings. Setting rel="canonical" tells search engines that this content
      has been syndicated from somewhere else.  This value will be the page's
      meta image or content's feed image.

date:
  _label: Published Date
  _has:
    input: default-text-with-override
    defaultField: defaultDate
    permissionToOverride:
      update: meta-tags
    help: The published timestamp.

_groups:
  settings:
    _label: Meta Url
    fields:
      - url
      - syndicatedUrl
      - date
