_description: |
  A list of podcasts. (This module requires minimum of 4 podcast selections in the list.)
items:
  _label: Items
  _placeholder:
    height: 200px;
    text: Podcast List
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 4
    props:
    -
      prop: podcast
      _label: URL
      _has:
        input: podcast-select
        validate:
          required: true
