_description: |
  A list of podcasts

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      required:
        field: fill
        operator: falsy
      max: 2
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: title
      _label: Title
      _has:
        input: text
        validate:
          max: 80
    -
      prop: imageUrl
      _has:
        validate:
          required: true
