_description: |
  List of podcasts -- Will autofill by category upon publish if left empty or less than 4 items.

items:
  _label: Podcasts
  _placeholder:
    height: 200px;
    text: Podcast List -- Autofills upon publish if left empty or less than 4 items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 4
    props:
    -
      prop: podcast
      _label: URL
      _has:
        input: podcast-select
        validate:
          required: true
