_version: 3.0
_description: |
  List of podcasts -- Will autofill by category upon publish if left empty or less than 4 items.

items:
  _label: Podcasts
  _placeholder:
    height: 200px;
    text: Podcast List -- Autofills upon publish if left empty or less than 4 items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 4
    props:
    -
      prop: podcast
      _label: URL
      _has:
        input: podcast-select
        validate:
          required: true

title:
  _label: Component's Title
  _has:
    input: text
    validate:
      required: true

primaryColor:
  _label: Component's Primary Color
  _has:
    input: text
    help: Override theme color with a hexadecimal(i.e. "#00CCB7") value above

isTitleFontColorDark:
  _label: Component's Title Font Color Dark
  _has:
    input: checkbox
    help: If you chose a light title background color and can't see the title's text enable this option

showTitle:
  _label: Should the component's Title be visible
  _has:
    input: checkbox

showCallToActions:
  _label: Should the component's Call to Actions be visible
  _has:
    input: checkbox

backFillEnabled:
  _label: Enable automatic backfilling of Podcast items
  _has:
    input: checkbox
sectionFront:
  _label: Section Front
  _subscribe: sectionFront

_groups:
  settings:
    fields:
      - title
      - primaryColor
      - isTitleFontColorDark
      - showTitle
      - showCallToActions
      - backFillEnabled
