_version: 15.0
_description: |
  Use filters to auto-populate content or manually search and add curated content to the More Content Feed.

authors:
  _label: Authors
  _has:
    input: select
    list: authors
    multiple: true
    search: true
    keys:
      label: text
      value: text
  _reveal:
    field: populateFrom
    operator: ===
    value: byline

contentType:
  _label: Content type
  _has:
    validate:
      required: true
    input: checkbox-group
    options:
      - article
      - gallery
      - contest

componentTitle:
  _label: Component's Title
  _has:
    validate:
      required: true
      min: 4
      max: 80
    help: The title displayed on the component's view
    input: text

componentTitleVisible:
  _label: Show Component's Title
  _has:
    input: checkbox
    help: Show or hide the title displayed on the component's view

pageLength:
  _label: Page Size
  _has:
    help: Number of articles to load when "load more" is clicked
    input: text
    type: number

maxLength:
  _label: Maximum Number of Content Items
  _has:
    help: Limit the number of content items
    input: text
    type: number

autoPopulatedContentHeader:
  _label: Auto-Populated Content
  _has: static

populateFrom:
  _label: Populate content from?
  _has:
    validate:
      required: true
    input: radio
    options:
      -
        name: All Content
        value: all-content
      -
        name: Section Front
        value: section-front
      - tag
      -
        name: Contains Both Section Front and Tag
        value: section-front-and-tag
      -
        name: Contains Either Section Front or Tag
        value: section-front-or-tag
      - manual
      -
        name: Byline
        value: byline
  _reveal:
    field: populateFrom
    operator: '!=='
    values:
      - author

curatedContentHeader:
  _label: Curated Content
  _has: static

locationOfContentFeed:
  _label: Content Feed is on Homepage
  _has:
    help: Indicates whether content feed is located on the homepage
    validate:
      required: true
    input: radio
    options:
      - homepage
      - section-front
      - topic-page
      - author-page

station:
  _subscribe: stationName

sectionFront:
  _subscribe: sectionFront
  _label: Section Front Category
  _has:
    help: Section Front Category from which to pull content

primarySectionFront:
  _subscribe: primarySectionFront

sectionFrontManual:
  _label: Section Front Category
  _publish: sectionFront
  _reveal:
    field: populateFrom
    operator: ===
    values:
      - section-front
      - section-front-and-tag
      - section-front-or-tag
  _has:
    input: select
    search: true
    list: primary-section-fronts

secondarySectionFront:
  _subscribe: secondarySectionFront
  _label: Secondary Section Front
  _has:
    help: Secondary Section Front from which to pull content

secondarySectionFrontManual:
  _label: Secondary Section Front Category
  _publish: secondarySectionFront
  _reveal:
    field: populateFrom
    operator: ===
    values:
      - section-front
      - section-front-and-tag
      - section-front-or-tag
  _has:
    input: select
    search: true
    list: secondary-section-fronts

tag:
  _subscribe: tag
  _label: tag
  _has:
    help: Includes content from all tags inside the section set in the URL

tagManual:
  _label: Tag
  _placeholder:
    height: 600px
    text: Curated Category/Tag Page
    required: true
  _reveal:
    field: populateFrom
    operator: ===
    values:
      - tag
      - section-front-and-tag
      - section-front-or-tag
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Includes content from all tags inside the section set in the URL
    validate:
      required:
        field: populateFrom
        operator: ===
        values:
          - tag
          - section-front-and-tag
          - section-front-or-tag

excludeTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

excludeSectionFronts:
  _label: Exclude Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: primary-section-fronts

excludeSecondarySectionFronts:
  _label: Exclude Secondary Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: secondary-section-fronts

excludeSubscriptions:
  _label: Exclude Subscriptions
  _has:
    input: checkbox

items:
  _label: Items
  _has:
    input: complex-list
    help: Manually choose content to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideSubHeadline
      _label: Sub-Headline
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: overrideDate
      _label: Date content was first published
      _has:
        input: datepicker
        help: Date article was first published
    -
      prop: overrideSectionFront
      _label: Section Front
      _has:
        input: select
        search: true
        list: primary-section-fronts
    -
      prop: overrideContentType
      _label: Content Type
      _has:
        help: The type of media on the lede of the page
        input: radio
        options:
          - image
          -
            name: instagram
            value: instagram-post
          - brightcove
          - youtube
          - verizon-media
          -
            name: html embed
            value: html-embed
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

enableSharethrough:
  _label: Enable Sharethrough
  _has:
    input: checkbox

introComponents:
  _label: Intro Components
  _placeholder:
    text: Intro Component
    height: 100px
  _componentList:
    include:
    - html-embed

sharethroughTag:
  _component:
    include:
      - google-ad-manager

_groups:
  contentFeed:
    _label: Content Feed
    fields:
      - componentTitle
      - componentTitleVisible
      - enableSharethrough
      - pageLength
      - maxLength
      - autoPopulatedContentHeader
      - populateFrom
      - sectionFrontManual
      - secondarySectionFrontManual
      - tagManual
      - contentType
      - authors
      - excludeTags
      - excludeSectionFronts
      - excludeSecondarySectionFronts
      - excludeSubscriptions
      - curatedContentHeader
      - items
    _placeholder:
      height: 100px
      ifEmpty: populateFrom
  header:
    _label: Content Feed Title
    fields:
      - componentTitle
      - componentTitleVisible
