_version: 7.0
_description: |
  A list of ten latest related articles from all content or filtered by article type, tag, or manually populated.
  The articles will be filtered by the section front of the URL, (ex: /sports/football with tags "NFL" and
  "National News" will only show sports stories that have either of those tags).

contentType:
  _label: Content type
  _has:
    validate:
      required: true
    input: checkbox-group
    options:
      - article
      - gallery

pageLength:
  _label: Page Size
  _has:
    help: Number of articles to load when "load more" is clicked
    input: text
    type: number

populateFrom:
  _label: Populate content from?
  _has:
    validate:
      required: true
    input: radio
    options:
      -
        name: All Content
        value: all-content
      -
        name: Section Front
        value: section-front
      - tag
      - manual

locationOfContentFeed:
  _label: Content Feed is on Homepage
  _has:
    help: Indicates whether content feed is located on the homepage
    validate:
      required: true
    input: radio
    options:
      - homepage
      - section-front
      - topic-page

sectionFront:
  _subscribe: sectionFront
  _label: Section Front Category
  _has:
    help: Section Front Category from which to pull content

sectionFrontManual:
  _label: Section Front Category
  _publish: sectionFront
  _reveal:
    field: populateFrom
    operator: ===
    value: section-front
  _has:
    input: select
    search: true
    list: primary-section-fronts

secondarySectionFront:
  _subscribe: secondarySectionFront
  _label: Secondary Section Front
  _has:
    help: Secondary Section Front from which to pull content

secondarySectionFrontManual:
  _label: Secondary Section Front Category
  _publish: secondarySectionFront
  _reveal:
    field: populateFrom
    operator: ===
    value: section-front
  _has:
    input: select
    search: true
    list: secondary-section-fronts

tag:
  _subscribe: tag
  _label: tag
  _has:
    help: Includes content from all tags inside the section set in the URL

tagManual:
  _label: Tag
  _placeholder:
    height: 600px
    text: Curated Category/Tag Page
    required: true
  _reveal:
    field: populateFrom
    operator: ===
    value: tag
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Includes content from all tags inside the section set in the URL
    validate:
      required:
        field: populateFrom
        operator: ===
        value: tag

tagInfo:
  _label: Tag Info
  _placeholder:
    height: 274px
    text: More Info on Tag
    required: true
  _reveal:
    field: populateFrom
    operator: ===
    value: tag
  _has:
    input: text
    help: Tag Description / More Info (Will be shown in right rail)

filterTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

filterSecondarySectionFronts:
  _label: Exclude Secondary Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: secondary-section-fronts

items:
  _label: Items
  _has:
    input: complex-list
    help: Manually choose content to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideSubHeadline
      _label: Sub-Headline
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: overrideDate
      _label: Date content was first published
      _has:
        input: datepicker
        help: Date article was first published
    -
      prop: overrideSectionFront
      _label: Section Front
      _has:
        input: select
        search: true
        list: primary-section-fronts
    -
      prop: overrideContentType
      _label: Content Type
      _has:
        help: The type of media on the lede of the page
        input: radio
        options:
          - image
          -
            name: instagram
            value: instagram-post
          - brightcove
          - youtube
          - verizon-media
          -
            name: html embed
            value: html-embed
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

introComponents:
  _label: Intro Components
  _placeholder:
    text: Intro Component
    height: 100px
  _componentList:
    include:
    - html-embed

contentCollectionLogoSponsorship:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager

_groups:
  contentFeed:
    _label: Content Feed
    fields:
      - pageLength
      - populateFrom
      - sectionFrontManual
      - secondarySectionFrontManual
      - tagManual
      - tagInfo
      - items
      - contentType
      - filterTags
      - filterSecondarySectionFronts
    _placeholder:
      height: 100px
      ifEmpty: populateFrom
