_description: |
  Brightcove Live video embed

video:
  _label: Video
  _has:
    input: static
    validate:
      required: true

player:
  _label: Video Player
  _has: brightcove-player

searchVideo:
  _label: Search for video
  _has:
    input: brightcove-search
    webLabel: Search
    live: true

updateVideo:
  _label: Update video
  _has:
    input: static
  _reveal:
    field: video
    operator: truthy

autoplayUnmuted:
  _label: Autoplay / unmuted (Happy Birthday Videos Only)
  _has: checkbox

clickToPlay:
  _label: Click to play
  _has: checkbox

showTitle:
  _label: Show video title?
  _has: checkbox

_groups:
  videoSettings:
    _label: Brightcove Live Video
    _placeholder:
      text: Brightcove Live Video
      height: 30px;
      ifEmpty: searchVideo AND video
    fields:
      - video (Update video)
      - player (Update video)
      - showTitle (Update video)
      - autoplayUnmuted (Update video)
      - clickToPlay (Update video)
      - updateVideo (Update video)
      - searchVideo (Search for video)
