_description: |
  Brightcove Live video embed

video:
  _label: Video
  _has:
    input: static
    validate:
      required: true

adConfig:
  _label: Ad Configuration
  _has:
    input: text
    help: The ID of the live ad configuration. Defaults to no ad configuration if not set.
    validate:
      required: true

searchVideo:
  _label: Search for video
  _has:
    input: brightcove-search
    webLabel: Search
    live: true

autoplayUnmuted:
  _label: Autoplay / unmuted (Happy Birthday Videos Only)
  _has: checkbox

clickToPlay:
  _label: Click to play
  _has: checkbox

showTitle:
  _label: Show video title?
  _has: checkbox

_groups:
  videoSettings:
    _label: Brightcove Live Video
    _placeholder:
      text: Brightcove Live Video
      height: 30px;
      ifEmpty: searchVideo AND video
    fields:
      - video (Video settings)
      - adConfig (Video settings)
      - showTitle (Video settings)
      - autoplayUnmuted (Video settings)
      - clickToPlay (Video settings)
      - searchVideo (Search for video)
