_description:
  A page to house your events

headline:
  _label: Event Headline
  _subscribe: eventHeadline
  _placeholder:
    height: 40px
    text: Event Headline
    required: true
  _has:
    input: inline
    buttons:
      - italic
      - strike
    validate:
      required: true
    help: Appears as event's title

subHeadline:
  _label: Event Sub Headline
  _subscribe: eventSubHeadline
  _placeholder:
    height: 40px
    text: Event Sub Headline
    required: true
  _has:
    input: inline
    buttons:
      - italic
      - strike
    validate:
      required: false
    help: Appears under event's title

lead:
  _label: Event Lead
  _placeholder:
    text: Event Lead
    height: 600px
  _componentList:
    fuzzy: false
    include:
      - image
      - instagram-post
      - brightcove
      - brightcove-live
      - youtube
      - html-embed
      - omny
      - verizon-media
    validate:
      max: 1
      required: true

sideShare:
  _component:
    include:
      - share

tags:
  _component:
    include:
      - tags

adTags:
  _component:
    include:
      - ad-tags

startDate:
  _label: Event Date
  _has:
    input: datepicker
    validate:
      required: true

startTime:
  _label: Event Time
  _has:
    input: timepicker
    validate:
      required: true

location:
  _label: Event Location
  _placeholder:
    height: 20px
    text: Event Location
    required: true
  _has:
    input: wysiwyg
    type: multi-line
    buttons:
      - bold
      - italic
      - strike
    rows: 4
    validate:
      required: true
    help: the place and address of the event

content:
  _label: Event Content
  _placeholder:
    text: Event Content
    height: 600px
  _componentList:
    fuzzy: true
    validate:
      required: true
    include:
      - paragraph
      - presented-by
      - subheader
      - image
      - tweet
      - facebook-post
      - instagram-post
      - youtube
      - html-embed
      - brightcove
      - inline-related
      - omny
      - verizon-media

_groups:
  publishedDate:
    fields:
      - startDate
      - startTime
    _placeholder:
      text: Event Date & Time
      height: 20px
      ifEmpty: startDate or startTime
