_description: |
  Embeds a Facebook post via the post's URL, visible in view mode.

url:
  _label: URL
  _placeholder:
    height: 30px
    text: Facebook Post
  _has:
    input: text
    type: url
    help: http://www.facebook.com/username/posts/ID
