_confirmRemoval: true

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdUnderLatestModule:
  _component:
    include:
      - google-ad-manager

moreContentFeed:
  _component:
    include:
      - more-content-feed
