_confirmRemoval: true

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdUnderLatestModule:
  _component:
    include:
      - google-ad-manager

podcastList:
  _component:
    include:
      - podcast-list

moreContentFeed:
  _component:
    include:
      - more-content-feed

stationsCarousel:
  _placeholder:
    text: Stations Carousel
    height: 300px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - stations-carousel

mainContent:
  _placeholder:
    text: Main Content
    height: 100px
  _componentList:
    include:
    - multi-column

latestContent:
  _component:
    include:
      - latest-content

latestVideos:
  _component:
    include:
      - latest-videos
