_confirmRemoval: true

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

mainContent:
  _placeholder:
    text: Main Content
    height: 100px
    required: true
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
    - multi-column
    - google-ad-manager
    - podcast-list
    - more-content-feed
    - stations-carousel
    - latest-content
    - latest-videos
