_confirmRemoval: true

title:
  _label: Title
  _has:
    input: text

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdUnderLatestModule:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager
