_description: |
  This is the site header at the top of every page. It displays the site logo, navigational links, account button, and search button.
_confirmRemoval: true
_permission:
  update: navigation

headerLinks:
  _label: Links
  _placeholder:
    text: Links
    height: 100
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: Nav Top Categories Url
        _has:
          input: text
          type: url
          validate:
            required: false
      -
        prop: drawer
        _label: Does this category have a drawer/tray/dropdown menu?
        _has:
          input: checkbox
          validate:
            required: true
      -
        prop: text
        _label: Nav Top Categories Text
        _has:
          input: text
          enforceMaxlength: true
          validate:
            required: true
            max: 13
            maxMessage: This field must be 13 or fewer characters long
      -
        prop: list
        _label: Drawer Sub Nav
        _has:
          input: complex-list
          validate:
            required: false
          props:
            -
              prop: text
              _label: Drawer Sub Nav Text
              _has:
                input: text
                enforceMaxlength: true
                validate:
                  required: true
                  max: 25
                  maxMessage: This field must be 25 or fewer characters long
            -
              prop: url
              _label: Drawer Sub Nav Url
              _has:
                input: text
                type: url
                validate:
                  required: false
            -
              prop: list
              _label: Drawer Sub Nav Links
              _has:
                input: complex-list
                validate:
                  required: false
                props:
                  -
                    prop: url
                    _label: Drawer Sub Category Link Url
                    _has:
                      input: text
                      type: url
                      validate:
                        required: true
                  -
                    prop: text
                    _label: Drawer Sub Category Link Text
                    _has:
                      input: text
                      enforceMaxlength: true
                      validate:
                        required: true
                        max: 25
                        maxMessage: This field must be 25 or fewer characters long

_groups:
  settings:
    fields:
      - headerLinks
