_description: |
  This is the station footer above the main footer.

_confirmRemoval: true
_permission:
  update: station-footer

footerLinks:
  _label: Footer Link collection
  _placeholder:
    height: 100px
    text: Add Footer Links
  _has:
    input: complex-list
    filter: true
    props:
    -
      prop: text
      _label: Link Text
      _has:
        input: text
        help: No more than 25 characters
        validate:
          required: true
    -
      prop: url
      _label: URL
      _has:
        input: text
        validate:
          required: true
          pattern: ^(https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,}\.[a-z]{2,}|\/)([-a-zA-Z0-9@:%_\+.~#?&//=]*)$
          patternMessage: e.g. http://domain.com/path or /path

copyright:
  _label: Copyright Text
  _placeholder:
    height: 14px
    text: Copyright Text
  _has:
    input: inline

_groups:
  settings:
    fields:
      - footerLinks
