_description: |
  More content feed right rail

contentCollectionLogoSponsorship:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager
