_description: |
  More content feed right rail

locationOfRightRail:
  _label: Where is this right rail located?
  _has:
    help: Indicates where the right rail is located
    validate:
      required: true
    input: radio
    options:
      - homepage
      - section-front
      - topic-page
      - author-page

contentCollectionLogoSponsorship:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager

_groups:
  rightRail:
    _label: Right Rail
    fields:
      - locationOfRightRail
    _placeholder:
      height: 100px
      ifEmpty: tagInfo
