'use strict';
/**
 * This file is intended to mock data comming from the API.
 */

const editorials = [
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WJZ-AM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: false,
        sports: true,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: false,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: false
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WJZ-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: false,
        sports: true,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: false,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: false
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WAAF-FM',
      feeds: {
        ac: false,
        rock: true,
        urban: false,
        hot_ac: false,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: false,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: false
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WMJX-FM',
      feeds: {
        ac: true,
        rock: true,
        urban: false,
        hot_ac: false,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: false
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WEEI-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: false,
        sports: true,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: false,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: false
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WEEI-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: false,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: false,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: false
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WODS-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: false,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: true,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    },
    {
      id: Math.floor(Math.random() * 100),
      callsign: 'WWBX-FM',
      feeds: {
        ac: false,
        rock: false,
        urban: false,
        hot_ac: true,
        sports: false,
        country: false,
        hip_hop: false,
        r_and_b: false,
        trending: true,
        news_talk: false,
        adult_hits: false,
        chr_top_40: false,
        throwbacks: false,
        alternative: false,
        classic_hits: false,
        classic_rock: false,
        hot_ac_top_40_chr: true
      }
    }
  ],
  newStationFeed = () => ({
    id: Math.floor(Math.random() * 100),
    callsign : '',
    feeds: {
      ac: false,
      rock: false,
      urban: false,
      hot_ac: false,
      sports: false,
      country: false,
      hip_hop: false,
      r_and_b: false,
      trending: false,
      news_talk: false,
      adult_hits: false,
      chr_top_40: false,
      throwbacks: false,
      alternative: false,
      classic_hits: false,
      classic_rock: false,
      hot_ac_top_40_chr: false
    },
    market: '',
    rdc_domain: '',
    call_letters: ''
  });

module.exports = { editorials, newStationFeed };
