_description: |
  Stations by genre directory page

googleInlineAd:
  _component:
    include:
      - google-ad-manager

stationsList:
  _component:
    include:
      - stations-list

stationsListTruncated:
  _component:
    include:
      - stations-list
