_description: A listing of events

# Properties
curatedEvents:
  _label: Add Event
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: URL
        _has:
          input: content-search
          validate:
            required: true
  _placeholder:
    text: Add Event
    height: 60px
    required: true