/**
 *
 * VueTranspiler Class
 *
 * Used to transpile HTML generated by handlebars into HTML for use by Vue.
 *
 */

import { prepare } from '../../../app/services/universal/spaLink'

export default class {
  /**
   *
   * Transpiles html generated by handlebars into html compatible with vue logic.
   *
   * @param {string} handlebarsHtml - HTML generated by handlebars templates.
   * @param {object} locals - clay locals
   * @returns {string} - Vue compatible HTML.
   */
  transpile (handlebarsHtml, locals) {
    let transpiledHtml = handlebarsHtml

    transpiledHtml = this._prepLinksForSpaRouter(transpiledHtml, locals)

    return transpiledHtml
  }

  /**
   *
   * Adds classes to appropiate <a> tags for SPA router logic to hook into.
   *
   * @param {string} html - HTML to update <a> tags in.
   * @param {object} locals - clay locals
   * @returns {string} - HTML with updated links.
   */
  _prepLinksForSpaRouter (html, locals) {
    const doc = new DOMParser().parseFromString(html, 'text/html')

    prepare(doc, locals.ENTERCOM_DOMAINS)

    return doc.body.innerHTML
  }
}
