
col1:
  _placeholder:
    height: 150px
  _componentList:
    renderOrder: 1
    include:
      - section-lead

col2:
  _placeholder:
    height: 150px
  _componentList:
    renderOrder: 2
    include:
      - latest-recirculation

col3:
  _placeholder:
    height: 150px
  _componentList:
    fuzzy: true
    renderOrder: 3
    include:
      - minified-content-feed

mediumRectangleTop:
  _component:
    include:
      - google-ad-manager
