
leftCol:
  _placeholder:
    height: 150px
  _componentList:
    include:
      - section-lead # TODO: modify section-lead to be in multi-col component

middleCol:
  _placeholder:
    height: 150px
  _componentList:
    include:
      - latest-recirculation # TODO: modify latest-recirc to handle being on homepage

rightCol:
  _placeholder:
    height: 150px
  _componentList:
    fuzzy: true
    include:
      - paragraph # TODO: replace with top-stories component when it's created
      - blockquote

googleAdHalfPage:
  _component:
    include:
      - google-ad-manager

googleAdBillboard:
  _component:
    include:
      - google-ad-manager
