_description: |
  newsletter sign up

title:
  _has:
    input: text
    help: i.e “Get [Station Newsletter Title] Delivered to your Inbox” | Get The Daily J Delivered to your Inbox

layoutType:
  _has:
    input: inline
    type: text

successTitle:
  _has:
    input: inline
    type: text
successMsg:
  _has:
    input: inline
    type: text
