_description: |
  A list of five latest related articles by article type, tag, or manually populated.

populateBy:
  _label: Populate articles by article type or tag?
  _has:
    validate:
      required: true
    input: radio
    options:
      - article type
      - tag
      - manual

articleType:
  _subscribe: articleType
  _label: Article Type
  _has:
    help: Article Type from which to pull articles

tag:
  _label: Tag
  _reveal:
    field: populateBy
    operator: ===
    value: tag
  _has:
    input: text
    help: Tag from which to pull articles
    validate:
      required:
        field: populateBy
        operator: ===
        value: tag

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 5
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

_groups:
  latestRecirculationItems:
    fields:
      - populateBy
      - articleType
      - tag
      - items
    _placeholder:
      ifEmpty: 'items.url'
      height: 100px
      text: Latest Story(s)
