_version: 1.1
_description: |
  Adds `<title>`, `twitter:title`, and `og:title` tags to the head.

defaultTitle:
  _subscribe: pageTitle

defaultOgTitle:
  _subscribe: ogTitle

defaultTwitterTitle:
  _subscribe: twitterTitle

defaultKilnTitle:
  _subscribe: pageListTitle

title:
  _label: Title
  _has:
    input: default-text-with-override
    defaultField: defaultTitle
    permissionToOverride:
      update: meta-tags
    validate:
      required: true
    help: >-
      This will vary based off content type.  For instance in an article this
      will be the seo, short or primary headlines.

ogTitle:
  _label: Open Graph Title
  _has:
    input: default-text-with-override
    defaultField: defaultOgTitle
    permissionToOverride:
      update: meta-tags
    help: >-
      This value will vary based off content type.  For instance in an article
      this will be the primary headline.

twitterTitle:
  _label: Twitter Title
  _has:
    input: default-text-with-override
    defaultField: defaultTwitterTitle
    permissionToOverride:
      update: meta-tags
    help: >-
      This value will vary based off content type.  For instance in an article
      this will be the short headline.

kilnTitle:
  _label: Kiln Title
  _publish: kilnTitle # set title of page in page list
  _has:
    input: default-text-with-override
    defaultField: defaultKilnTitle
    permissionToOverride:
      update: meta-tags
    validate:
      required: true
    help: >-
      This value will vary based off content type.  For instance in an article
      this will be the primary headline.

_groups:
  settings:
    _label: Meta Title
    fields:
      - title
      - ogTitle
      - twitterTitle
      - kilnTitle
