_version: 1.0
_description: |
  A list of 6 trending stories

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      required:
        field: fill
        operator: falsy
      min: 6
      max: 6
    props:
    -
      prop: url
      _label: URL -- Requires 6 Entries
      _has:
        input: content-search
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

_groups:
  trendingItems:
    _label: hello
    _placeholder:
      ifEmpty: items.url and fill
      height: 100px
      text: Trending Stories -- Requires 6 Entries
    fields:
      - items
