_description: |
  A list of one or more trending stories

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      required:
        field: fill
        operator: falsy
      max: 6
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

_groups:
  trendingItems:
    fields:
    - items
    _placeholder:
      ifEmpty: items.url and fill
      height: 100px
      text: Trending Story(s)
