_description: |
 Latest content for entertainment, news and sports
    * Maximum number of articles is 3
    
  entertainmentItems:
    _label: Entertainment articles
    _has:
      input: complex-list
      enforceMaxlength: true
      validate:
        max: 3
      props:
      -
        prop: url
        _label: URL
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: overrideTitle
        _label: Headline Override
        _has:
          input: text
          validate:
            max: 80
      -
        prop: urlIsValid
        _has:
          validate:
            required: true

  sportsItems:
    _label: Sports articles
    _has:
      input: complex-list
      enforceMaxlength: true
      validate:
        max: 3
      props:
      -
        prop: url
        _label: URL
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: overrideTitle
        _label: Headline Override
        _has:
          input: text
          validate:
            max: 80
      -
        prop: urlIsValid
        _has:
          validate:
            required: true

  newsItems:
    _label: News articles
    _has:
      input: complex-list
      enforceMaxlength: true
      validate:
        max: 3
      props:
      -
        prop: url
        _label: URL
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: overrideTitle
        _label: Headline Override
        _has:
          input: text
          validate:
            max: 80
      -
        prop: urlIsValid
        _has:
          validate:
            required: true


_groups:
  latestContentItems:
    fields:
    - entertainmentItems
    - sportsItems
    - newsItems

    _placeholder:
      ifEmpty: entertainmentItems and sportsItems and newsItems
      height: 100px
      text: Latest articles(s)
