_version: 2.0
_description: |
  A list of five latest related articles by article type, tag, or manually populated.
contentType:
  _label: Content type
  _has:
    validate:
      required: true
    input: checkbox-group
    options:
      - article
      - gallery

sportsItems:
  _label: Sports Articles
  _placeholder:
    height: 150px;
    text: Sports Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
musicItems:
  _label: Music Articles
  _placeholder:
    height: 150px;
    text: Music Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

newsItems:
  _label: News Articles
  _placeholder:
    height: 150px;
    text: News Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

filterTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: filterTag
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

filterSecondaryArticleTypes:
  _label: Exclude Secondary Article Types
  _has:
    input: checkbox-group
    options:
      - Pop
      - Alternative
      - Country
      -
        name: Hip-Hop R&B
        value: Hip-Hop R&B
      - Rock
      - Icons
      - Entertainment News
      - Movies
      - Television
      - National News
      - Politics
      - Local Politics
      - Small Business Pulse
      - NFL
      - MLB
      - NBA
      - NHL
      - NCAA Football
      - NCAA Basketball
      -
        name: MMA & WWE
        value: MMA & WWE

_groups:
  settings:
    fields:
      - contentType
      - filterTags
      - filterSecondaryArticleTypes
  musicItems:
    fields:
      - musicItems
  newsItems:
    fields:
      - newsItems
  sportsItems:
    fields:
      - sportsItems
