_description: |
  A list of five latest related articles by article type, tag, or manually populated.

sportsItems:
  _label: Sports Articles
  _placeholder:
    height: 150px;
    text: Sports Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
musicItems:
  _label: Music Articles
  _placeholder:
    height: 150px;
    text: Music Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

newsItems:
  _label: News Articles
  _placeholder:
    height: 150px;
    text: News Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

_groups:
  musicItems:
    fields:
      - musicItems
  newsItems:
    fields:
      - newsItems
  sportsItems:
    fields:
      - sportsItems
