_version: 5.0
_description: |
  A list of five latest related articles by article type, tag, or manually populated.

componentTitle:
  _label: Component's Title
  _has:
    validate:
      required:
        field: componentTitleVisible
        operator: truthy
      min: 4
      max: 80
    help: The title displayed on the component's view
    input: text

componentTitleVisible:
  _label: Show Component's Title
  _has:
    input: checkbox
    help: Show or hide the title displayed on the component's view

contentType:
  _label: Content type
  _has:
    validate:
      required: true
    input: checkbox-group
    options:
      - article
      - gallery
  _reveal:
    field: hasCustomColumns
    operator: falsy

sportsItems:
  _label: Sports Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
musicItems:
  _label: Music Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

newsItems:
  _label: News Articles
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

filterTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: filterTag
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags
  _reveal:
    field: hasCustomColumns
    operator: falsy

filterSecondarySectionFronts:
  _label: Exclude Secondary Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: secondary-section-fronts
  _reveal:
    field: hasCustomColumns
    operator: falsy


_groups:
  settings:
    fields:
      - componentTitle
      - componentTitleVisible
      - hasCustomColumns
      - contentType
      - filterTags
      - filterSecondarySectionFronts
  musicItems:
    fields:
      - musicItems
  newsItems:
    fields:
      - newsItems
  sportsItems:
    fields:
      - sportsItems

hasCustomColumns:
  _label: Allow Custom Columns
  _has:
    input: checkbox
    help: This option enables advanced customization options for each column 

firstColumn:
  _placeholder:
    height: 168px
  _componentList:
    renderOrder: 1
    include:
      - latest-content-column
    validate:
      max: 1
      required:
        field: hasCustomColumns
        operator: truthy

secondColumn:
  _placeholder:
    height: 168px
  _componentList:
    renderOrder: 2
    include:
      - latest-content-column
    validate:
      max: 1
      required:
        field: hasCustomColumns
        operator: truthy

thirdColumn:
  _placeholder:
    height: 168px
  _componentList:
    renderOrder: 3
    include:
      - latest-content-column
    validate:
      max: 1
      required:
        field: hasCustomColumns
        operator: truthy
      