_version: 1.0

_description: |
  This is the image component specific to New York Magazine.

  * Only allows images from Mediaplay (our image server) to be added.
  * This component automatically adjusts the width and height based on the size selected.
  * Pulls in caption from Mediaplay if the user hits the magic button (note: changes made in this component _do not_ sync back to Mediaplay).
  * Automatically pulls in credit from Mediaplay on save.

url:
  _has:
    input: advanced-image-upload
    uploadLabel: Upload Image Attachment
    uploadHelp: Choose an image file from your computer
caption:
  _label: Caption
  _has:
    input: wysiwyg
    buttons:
      - link
      - bold
      - italic
credit:
  _label: Credit
  _has:
    input: wysiwyg
    buttons:
      - link
      - bold
      - italic
    help: Add in credit
alt:
  _label: Alt Text
  _has:
    input: text
    help: Alternative text for screen readers
    validate:
      required: true
creditOverride:
  _label: Credit Override
  _has:
    input: wysiwyg
    buttons:
      - bold
      - italic
      - link
imageLink:
  _label: URL
  _has:
    input: text
    type: url
    help: Add a link to the image

_groups:
  inlinestuff:
    fields:
      - url
      - rendition
      - caption
      - credit
      - alt
      - borderToggle
    _label: Image
    _placeholder:
      text: New Image
      height: 250px
      ifEmpty: url
  settings:
    fields:
      - imageLink
      - creditOverride
