_description: |
  A component that displays a list of local stations.

overrideTitle:
  _label: Override default title
  _has:
    input: inline

sectionFront:
  _label: Section Front
  _subscribe: sectionFront
  _has:
    input: static
    text: ${sectionTitle}

genre:
  _label: Genre
  _subscribe: genre
  _has:
    input: static
    text: ${genre}

filterStationsBy:
  _label: Filter stations by?
  _has:
    validate:
      required: true
    input: radio
    options:
      -
        name: Local Stations (filter by market)
        value: market
      -
        name: Section Front (Near You)
        value: section-front
      -
        name: Genre (Near You)
        value: genre

_groups:
  settings:
    fields:
      - overrideTitle
      - filterStationsBy
    _placeholder:
      text: Stations Carousel
      height: 315px
      ifEmpty: filterStationsBy
