FROM node:10.16.3

ENV HOME=/usr/src/app

COPY package.json $HOME/
COPY package-lock.json $HOME/

WORKDIR $HOME/
RUN npm ci

# Build application source into image and run container
COPY . $HOME/

RUN npm run build-production
RUN npm install pm2 -g
RUN mkdir .pm2 && chmod -R 777 .pm2

EXPOSE 3001

USER node

CMD ["pm2-runtime", "app.js"]
