configmap:
  data:
    APPLE_NEWS_ENABLED: "FALSE"
    APPLE_NEWS_PREVIEW_ONLY: "FALSE"
    AWS_S3_BUCKET: "radioimg-stg"
    AWS_S3_CDN_HOST: "stg-images.radio.com"
    BRIGHTCOVE_ACCOUNT_ID: "5757251889001"
    CLAY_ACCESS_KEY: "accesskey"
    CLAY_BUS_HOST: "redis://redis:6379"
    CLAY_LOG_PRETTY: "true"
    CLAY_PROVIDER: "google"
    CLAY_SITE_HOST: "clay.radio.com"
    CLAY_SITE_NAME: "Clay Demo"
    CLAY_SITE_PORT: "443"
    CLAY_SITE_PROTOCOL: "https"
    CLAY_SITE_SHORTKEY: "cd"
    CLAY_STORAGE_POSTGRES_CACHE_HASH: "mydb:h"
    CLAY_STORAGE_POSTGRES_HOST: "postgres"
    COGNITO_CONSUMER_DOMAIN: "https://clay.radio.com"
    COGNITO_CONSUMER_REGION: "us-east-1"
    COGNITO_SERVER: "https://etm.auth.us-east-1.amazoncognito.com"
    DOUBLECLICK_BANNER_TAG: "ENT.TEST"
    ELASTIC_HOST: "http://elasticsearch:9200"
    EMBEDLY_ENDPOINT: "NEED_TO_FILL_IN"
    EMBEDLY_KEY: "NEED_TO_FILL_IN"
    ENABLE_GZIP: "true"
    FACEBOOK_CALLBACK_URL: "https://radio.auth.us-east-1.amazoncognito.com/oauth2/token"
    GOOGLE_AD_REFRESH_INTERVAL: "120000"
    GOOGLE_OVERRIDES_PERMISSIONS: "true"
    GOOGLE_PROFILE_URL: "https://www.googleapis.com/oauth2/v3/userinfo"
    IMPORT_CONTENT_URL: "http://host.docker.internal:3000/import-content"
    INLINE_EDIT_SCRIPTS: "true"
    INLINE_EDIT_STYLES: "true"
    IP_ADDRESS: "0.0.0.0"
    LOG: "info"
    LYTICS_API_URL: "https://api.lytics.io/api"
    NODE_ENV: "local"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    PORT: "3001"
    REDIS_HASH: "mydb:h"
    REDIS_HOST: "tcp://redis:6379"
    REDIS_SESSION_HOST: "redis://redis:6379"
    SECTION_FRONTS: "music,news,sports"
    STATIC_ASSET_MAX_AGE: "0"
    URPS_AUTHORIZATIONS_URL: "http://roc-urps-api-sbx.pcwpuime6w.us-west-1.elasticbeanstalk.com"
    URPS_HAS_AUTH_LAYER: "false"
    WEB_PLAYER_HOST: "https://assets.radio.com/webplayer"

