name: ${CLAY_SITE_NAME}
host: ${CLAY_SITE_HOST}
path: ''
assetDir: public
assetPath: ''
port: 80
protocol: http
shortKey: ${CLAY_SITE_SHORTKEY}
webPlayerHost: ${WEB_PLAYER_HOST}
brightcoveAccountId: 1418490336
brightcovePlayerId: 90eeiglcU
googleContainerId: 'PN754S7'

