name: ${CLAY_SITE_NAME}
host: ${CLAY_SITE_HOST}
path: ''
assetDir: public
assetPath: ''
port: ${CLAY_SITE_PORT}
protocol: ${CLAY_SITE_PROTOCOL}
shortKey: ${CLAY_SITE_SHORTKEY}
webPlayerHost: ${WEB_PLAYER_HOST}
brightcoveAccountId: ${BRIGHTCOVE_ACCOUNT_ID}
brightcovePlayerId: 9klBjvbUGf
brightcoveLivePlayerId: jTYbBkfzD
googleContainerId: 5XL9KZ5
verizonMediaCompanyId: 5b4617f33a85ab2357ed40fb
verizonMediaPlayerId: 5b4617f3e880db42b536cecc
radiocomDefaultImg: 'https://images.radio.com/aiu-media/og_775x515_0.jpg'
sharethroughPlacementKey: mxkcXkpf326JUS8ZHS35e6U5
apsPubId: '3728'
apsBidTimeout: 1000
apsLoadTimeout: 2500
