name: ${CLAY_SITE_NAME}
host: ${CLAY_SITE_HOST}
path: ''
assetDir: public
assetPath: ''
port: 80
protocol: http
shortKey: ${CLAY_SITE_SHORTKEY}
webPlayerHost: ${WEB_PLAYER_HOST}
brightcoveAccountId: 5757251889001
brightcovePlayerId: 9klBjvbUGf
googleContainerId: 5XL9KZ5
verizonMediaCompanyId: 5b4617f33a85ab2357ed40fb
verizonMediaPlayerId: 5b4617f3e880db42b536cecc
