name: ${CLAY_SITE_NAME}
host: ${CLAY_SITE_HOST}
path: ''
assetDir: public
assetPath: ''
port: ${CLAY_SITE_PORT}
protocol: ${CLAY_SITE_PROTOCOL}
shortKey: ${CLAY_SITE_SHORTKEY}
webPlayerHost: ${WEB_PLAYER_HOST}
brightcoveAccountId: ${BRIGHTCOVE_ACCOUNT_ID}
brightcovePlayerId: 9klBjvbUGf
googleContainerId: 5XL9KZ5
verizonMediaCompanyId: 5b4617f33a85ab2357ed40fb
verizonMediaPlayerId: 5b4617f3e880db42b536cecc

app: 'app.730a9183.js'

chunk-vendors: 'chunk-vendors.4b2935d4.js'
