name: ${CLAY_SITE_NAME}
host: ${CLAY_SITE_HOST}
path: ''
assetDir: public
assetPath: ''
port: 80
protocol: http
shortKey: ${CLAY_SITE_SHORTKEY}
webPlayerHost: ${WEB_PLAYER_HOST}
brightcoveAccountId: 5757251889001
brightcovePlayerId: 9klBjvbUGf
googleContainerId: 5XL9KZ5

app: 'app.34d3c7c1.js'

chunk-vendors: 'chunk-vendors.153e00a9.js'
