_description: |
  Google Ad Manager ad slots

adSize:
  _label: Ad Slot Size (Note** Responsive)
  _placeholder:
    height: 250px
    text: Ad Slot
    required: true
  _has:
    input: radio
    help: Choose the size of the Google Ad Manager ad slot in pixels
    options:
      -
        name: preferred (970x250)
        value: preferred
      -
        name: large leaderboard (970x90)
        value: large-leaderboard
      -
        name: leaderboard (728x90)
        value: leaderboard
      -
        name: half page (300x600)
        value: half-page
      -
        name: medium rectangle (300x250)
        value: medium-rectangle
      -
        name: mobile (320x50)
        value: mobile
      -
        name: logo sponsorship (100x35)
        value: logo-sponsorship
    validate:
      required: true
