_version: 1.0
_confirmRemoval: true

_description: |
  Google Ad Manager ad slots

adSize:
  _label: Ad Slot Size (Note** Responsive)
  _placeholder:
    height: 250px
    text: ${adSize} ad slot
    permanent: true
  _has:
    input: radio
    help: Choose the size of the Google Ad Manager ad slot in pixels
    options:
      -
        name: Billboard (970x250)
        value: billboard
      -
        name: Footer Billboard (970x250)
        value: footer-billboard
      -
        name: Super Leaderboard (970x90)
        value: super-leaderboard
      -
        name: Leaderboard (728x90)
        value: leaderboard
      -
        name: Half Page (300x600)
        value: half-page
      -
        name: Half Page Topic (300x600)
        value: half-page-topic
      -
        name: Medium Rectangle (300x250)
        value: medium-rectangle
      -
        name: Mobile Adhesion (320x50)
        value: mobile-adhesion
      -
        name: Logo Sponsorship (100x35)
        value: logo-sponsorship
      -
        name: Global Logo Sponsorship (100x35)
        value: global-logo-sponsorship
      -
        name: Content Collection / Topic Page / Author Page Logo Sponsorship (100x35)
        value: content-collection-logo-sponsorship
      -
        name: Article / Gallery Page Logo Sponsorship (100x35)
        value: content-page-logo-sponsorship
      -
        name: sharethroughTag
        value: sharethrough-tag
    validate:
      required: true
adPosition:
  _label: Ad Slot Position Target (DFP)
  _has:
    input: text
sticky:
  _label: Stick ad on Scroll
  _has:
    input: checkbox
adLocation:
  _label: Ad Slot Location Target (DFP)
  _has:
    input: radio
    options:
      -
        name: Above The Fold
        value: atf
      -
        name: Below The Fold
        value: btf
