items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 6
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
tag:
  _label: Tag
  _has:
    input: text
    validate:
      required:
        field: fill
        operator: truthy
    help: Tag from which to pull articles
sectionTitle:
  _label: Section Title
  _subscribe: sectiontitle

_groups:
  sectionVideos:
    fields:
    - items
    - tag
    _placeholder:
      ifEmpty: items.url and tag and sectionTitle
      height: 100px
      text: Section Videos
