_version: 2.0
_description: |
  A dynamically created slider for promoting recirculation of latest articles and galleries within the same.
_confirmRemoval: true

contentType:
  _label: Content type
  _has:
    validate:
      required: true
    input: checkbox-group
    options:
      - article
      - gallery

populateFrom:
  _label: Populate content from?
  _has:
    validate:
      required: true
    input: radio
    options:
      -
        name: All Content
        value: all-content
      -
        name: Section Front
        value: section-front
      - tag
      -
        name: Contains Both Section Front and Tag
        value: section-front-and-tag
      -
        name: Contains Either Section Front or Tag
        value: section-front-or-tag

sectionFront:
  _label: Section Front Category
  _publish: sectionFront
  _reveal:
    field: populateFrom
    operator: ===
    values:
      - section-front
      - section-front-and-tag
      - section-front-or-tag
  _has:
    input: select
    search: true
    list: primary-section-fronts

secondarySectionFront:
  _label: Secondary Section Front Category
  _publish: secondarySectionFront
  _reveal:
    field: populateFrom
    operator: ===
    values:
      - section-front
      - section-front-and-tag
      - section-front-or-tag
  _has:
    input: select
    search: true
    list: secondary-section-fronts

tag:
  _label: Tag
  _placeholder:
    height: 600px
    text: Curated Category/Tag Page
    required: true
  _reveal:
    field: populateFrom
    operator: ===
    values:
      - tag
      - section-front-and-tag
      - section-front-or-tag
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Includes content from all tags inside the section set in the URL
    validate:
      required:
        field: populateFrom
        operator: ===
        values:
          - tag
          - section-front-and-tag
          - section-front-or-tag

excludeTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

excludeSectionFronts:
  _label: Exclude Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: primary-section-fronts
  
excludeSecondarySectionFronts:
  _label: Exclude Secondary Section Fronts
  _has:
    input: select
    search: true
    multiple: true
    list: secondary-section-fronts

excludeSubscriptions:
  _label: Exclude Subscriptions
  _has:
    input: checkbox

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 10
    help: Manually choose articles to include
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: text
        help: Image url for article thumbnail
        type: url
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true

_groups:
  settings:
    _label: Latest Top Recirc
    fields:
      - contentType
      - populateFrom
      - sectionFront
      - secondarySectionFront
      - tag
      - excludeTags
      - excludeSectionFronts
      - excludeSecondarySectionFronts
      - excludeSubscriptions
