_description: |
  A component that handles tagging for ads.

  * Ad Tags function as a simple-list that is only visible when editing.
  *
  * A user can add and remove tags.
  *
  * Suggested tags will populate based on alphabetical order and popularity.
  *
  * Users can create new tags when populating this component.

items:
  _placeholder:
    text: Ad Tags
    height: 40px
  _has:
    input: simple-list
    badge: FR
    autocomplete:
      list: ad-tags
      allowRemove: true
      allowCreate: true
  _list_permission:
    create: create
    remove: remove
