_description: |
  A list of one or more related stories

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      required:
        field: backfill
        operator: falsy
      max: 2
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
backfill:
  _label: Backfill from tag
  _has:
    input: select
    options:
      -
        name: None
        value: 0
      - 1
      - 2
tag:
  _label: Tag
  _has:
    input: text
    validate:
      required:
        field: backfill
        operator: truthy
    help: Tag from which to pull articles
  _reveal:
    field: backfill
    operator: truthy
articleType:
  _subscribe: articleType

_groups:
  inlineRelatedItems:
    fields:
    - items
    - backfill
    - tag
    _placeholder:
      ifEmpty: items.url and backfill
      height: 100px
      text: Related Story(s)
