_version: 1.0
_description: |
  A list of one or more related stories

    * Maximum number of articles is 2

    ** Can be any combination of manual selection and fill from a tag

    * Set a fill if you prefer to automatically get articles from a specific tag

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      required:
        field: fill
        operator: falsy
      max: 2
    props:
    -
      prop: url
      _label: URL
      _has:
        input: content-search
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
          required:
            field: ignoreValidation
            operator: truthy
    -
      prop: overrideImage
      _label: Image Override
      _has:
        input: advanced-image-upload
        uploadLabel: Upload Image Attachment
        uploadHelp: Choose an image file from your computer to override image
        validate:
          required:
            field: ignoreValidation
            operator: truthy
    -
      prop: ignoreValidation
      _label: Bypass URL Validation?
      _has:
        input: checkbox
        help: Use this field if the destination of the URL entered is not a Radio.com content page. If checked, Headline and Image Override must be set manually.
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
fill:
  _label: "# of articles to fill from a tag"
  _has:
    input: select
    options:
      -
        name: None
        value: 0
      - 1
      - 2
tag:
  _label: Tag
  _has:
    input: text
    validate:
      required:
        field: fill
        operator: truthy
    help: Tag from which to pull articles
  _reveal:
    field: fill
    operator: truthy
sectionFront:
  _subscribe: sectionFront

_groups:
  inlineRelatedItems:
    fields:
    - items
    - fill
    - tag
    _placeholder:
      ifEmpty: items.url and fill
      height: 100px
      text: Related Story(s)
