content:
  _label: Events Listing Page Content
  _placeholder:
    text: Events Listing Content
    height: 600px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - events-lede
      - more-content-feed
