_version: 1.0
_permission:
  update: station-navigation

featuredLinks:
  _subscribe: featuredLinks

hideOnAirSchedule:
  _subscribe: hideOnAirSchedule

hidePodcastsLink:
  _subscribe: hidePodcastsLink

podcastsUrl:
  _subscribe: listenNavPodcastUrl