_description: |
  Brightcove video embed

videoId:
  _label: Video ID
  _has:
    input: brightcove-search
    webLabel: Search
    validate:
      required: true

newVideo:
  _label: Upload new video
  _has:
    input: brightcove-upload

showTitle:
  _label: Show video title?
  _has: checkbox

_groups:
  video:
    _label: Brightcove Video
    _placeholder:
      text: Brightcove Video
      height: 30px;
      ifEmpty: videoId
    fields:
      - showTitle
      - videoId (Search for video)
      - newVideo (Upload new video)
