_version: 1.0
_description: |
  Brightcove video embed

videoId:
  _label: Video ID
  _has:
    input: brightcove-search
    webLabel: Search
    validate:
      required: true

autoplayUnmuted:
  _label: Autoplay / unmuted (Happy Birthday Videos Only)
  _has: checkbox

clickToPlay:
  _label: Click to play
  _has: checkbox

showTitle:
  _label: Show video title?
  _has: checkbox

_groups:
  video:
    _label: Brightcove Video
    _placeholder:
      text: Brightcove Video
      height: 30px;
      ifEmpty: videoId
    fields:
      - videoId
      - autoplayUnmuted
      - clickToPlay
      - showTitle
