_version: 1.0
_description: |
  Brightcove video embed

video:
  _label: Video
  _has:
    validate:
      required: true

searchVideo:
  _label: Search for video
  _has:
    input: brightcove-search
    webLabel: Search

newVideo:
  _label: Upload new video
  _has:
    input: brightcove-upload

showTitle:
  _label: Show video title?
  _has: checkbox

_groups:
  videoSettings:
    _label: Brightcove Video
    _placeholder:
      text: Brightcove Video
      height: 30px;
      ifEmpty: searchVideo AND newVideo
    fields:
      - showTitle (Edit Video)
      - searchVideo (Search for video)
      - newVideo (Upload new video)
