_description: |
  A one-column layout for Clay.

head:
  _componentList:
    page: true
    include:
      - meta-title
      - meta-site
      - meta-image
      - meta-icons
      - meta-url
      - meta-tags

headLayout:
  _componentList:
    include:
      - favicon
      - meta-title
      - meta-url
      - meta-description
      - meta-image
      - meta-icons
      - meta-url
      - google-fonts

top:
  _componentList:
    include:
      - header
topSection:
  _componentList:
    page: true
    include:
      - station-nav
topAd:
  _componentList:
    include:
      - google-ad-manager
layoutHeader:
  _componentList:
    include:
      - google-ad-manager
pageHeader:
  _componentList:
    page: true
    include:
      - topic-page-header

banner:
  _componentList:
    include:
      - alert-banner

main:
  _componentList:
    page: true
    include:
      - post
      - general-content
secondary:
  _componentList:
    include:
      - generic-list

bottom:
  _componentList:
    include:
      - footer

bottomSection:
  _componentList:
    page: true
    include:
      - station-footer

bottomAd:
  _componentList:
    include:
      - google-ad-manager

kilnInternals:
  _componentList:
    internals: true
    include:
      - clay-kiln
static:
  _componentList:
    include:
      - web-player
      - chartbeat
