_version: 2.0
_description: |
  Youtube video embed for Clay. Can only be used for Youtube videos hosted by NYMag or Vulture. For externally hosted videos, use the Video component.
  For technical reasons, YouTube embeds don't display a preview in edit mode. Preview the video by previewing the full page (from the Clay toolbar). Embeds can display a specific video ID.

contentId:
  _label: YouTube Video ID or Playlist ID
  _publish: videoPlayerId
  _reveal:
    field: videoSource
    values:
      - video
      - playlist
  _has:
    input: text
    validate:
      required:
        field: videoSource
        values:
          - video
          - playlist

videoType:
  _label: Type
  _has:
    input: radio
    options:
      - Editorial
      - Related
      - Sponsored
    validate:
      required: true
      requiredMessage: Please select a video type

videoSource:
  _label: Source
  _has:
    input: radio
    options:
      -
        name: Video ID
        value: video
      -
        name: Playlist ID
        value: playlist
    validate:
      required: true
      requiredMessage: Please select "Video ID" to embed a specific YouTube video by id (e.g. "pHXVa0B6KFs"). Select Playlist ID to embed a playlist by id.
    help: Please select "Video ID" to embed a specific YouTube video by id (e.g. "pHXVa0B6KFs"). Select Playlist ID to embed a playlist by id.

playerHeadline:
  _label: Video Headline
  _has:
    input: text
  _reveal:
    field: videoType
    value: Related

playerCaption:
  _label: Video Caption
  _has: text

autoPlay:
  _label: Autoplay on Page Load
  _has: checkbox

autoPlayNextVideo:
  _label: Automatically start next video
  _has: checkbox
  _reveal:
    field: videoType
    operator: '!=='
    value: Sponsored

videoPlaylist:
  _label: Youtube Playlist (defaults to current site)
  _reveal:
    field: autoPlayNextVideo
    operator: truthy
  _has:
    input: text

playerBorderTopCTA:
  _label: Top Border Title
  _has: text

playerBorderTop:
  _label: Show Top Border
  _has: checkbox

playerBorderBottom:
  _label: Show Bottom Border
  _has: checkbox

_groups:
  inline:
    fields:
      - videoSource
      - contentId
      - videoType
      - playerHeadline
      - playerCaption
    _label: Youtube Video Player
    _placeholder:
      text: Youtube Video Player
      height: 100px
      ifEmpty: contentId

# set by bootstrap or first-run
videoLocation:
  help: For analytics, to tell what kind of page the video is on

# non-user-editable fields, set by model.js
previousTypeRelated:
  help: Toggle for displaying convenience-based changes to player borders based on previously selected video type. Set by model.js
videoValid:
  help: Used to decide whether or not to display a video in the template
  _placeholder:
    text: Invalid id ${contentId}. This video or playlist will not display.
    permanent: true
channelName:
  help: Name of the channel the video comes from. Used to decide whether or not to listen to GTM triggers for this video
videoTitle:
  help: Title of the video
videoThumbnail:
  help: maxres video thumbnail
videoDuration:
  help: video duration in seconds
