_version: 3.0
_confirmRemoval: true

title:
  _label: Title
  _publish:
    - sectionFront
    - ogTitle
    - pageListTitle
    - pageTitle
  _has:
    input: text
    validate:
      required:
        field: titleLocked
        operator: falsy
  _reveal:
    field: titleLocked
    operator: falsy

titleLocked:
  _label: Is title locked?
  _has: checkbox

primary:
  _label: Is this a primary section front?
  _has: checkbox
  _reveal:
    field: titleLocked
    operator: falsy

primarySectionFront:
  _publish:
    - primarySectionFront
  _reveal:
    field: primary
    operator: falsy
  _label: 'Primary Section Front:'
  _has:
    help: Choose the primary section front if this is a secondary section front
    input: select
    search: true
    list: primary-section-fronts
    validate:
      required:
        field: primary
        operator: falsy

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

sectionFrontContent:
  _placeholder:
    text: Main Content
    height: 100px
    required: true
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
    - google-ad-manager
    - multi-column
    - podcast-list
    - stations-carousel
    - two-column-component

_groups:
  settings:
    fields:
      - primary
      - primarySectionFront
      - title

stationName:
  _publish: stationName
  _label: Station Name
  _has: static
  _reveal:
    field: stationName
    operator: truthy
