_confirmRemoval: true

title:
  _label: Section Title
  _publish: sectionTitle
  _has:
    input: radio # @TODO: ON-156 make this static
    options:
      -
        name: Entertainment
        value: entertainment
      -
        name: News
        value: news
      -
        name: Sports
        value: sports
      -
        name: Podcasts
        value: podcasts
canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.
        
_groups:
  settings:
    fields:
      - title

# Component properties
sectionLead:
  _component:
    include:
    - section-lead

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager