_version: 4.0
_confirmRemoval: true

_pagePermissions:
  add-component: section-front
  remove-component: section-front

title:
  _label: Title
  _publish:
    - sectionFront
    - ogTitle
    - pageListTitle
    - pageTitle
  _has:
    input: text
    validate:
      required:
        field: revealSectionFrontControls
        operator: truthy
  _reveal:
    field: revealSectionFrontControls
    operator: truthy


titleLocked:
  _label: Is title locked?
  _has: checkbox

stationSlug:
  _label: Station Site Slug
  _publish:
    - sectionFront
    - ogTitle
    - pageListTitle
    - pageTitle

primary:
  _label: Is this a primary section front?
  _has: checkbox
  _reveal:
    field: revealSectionFrontControls
    operator: truthy

primarySectionFront:
  _publish:
    - primarySectionFront
  _reveal:
    field: primary
    operator: falsy
  _label: 'Primary Section Front:'
  _has:
    help: Choose the primary section front if this is a secondary section front
    input: select
    search: true
    list: primary-section-fronts
    validate:
      required:
        field: primary
        operator: falsy

includePodcastModule:
  _label: Include podcast module on page?
  _has: checkbox

podcastList:
  _component:
    include:
      - podcast-list


dividerContainer:
  _placeholder:
    text: Add Divider Title
    height: 30px
  _componentList:
    include:
      - divider

twoColumnComponent:
  _component:
    include:
      - two-column-component

stationsCarousel:
  _placeholder:
    text: Stations Carousel
    height: 300px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - stations-carousel

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

mainContent:
  _placeholder:
    text: Main Content
    height: 100px
    required: true
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
    - google-ad-manager
    - multi-column
    - podcast-list
    - stations-carousel
    - two-column-component

_groups:
  settings:
    fields:
      - stationName
      - primary
      - primarySectionFront
      - title

stationName:
  _publish: stationName
  _label: Station Name
  _has: static
  _reveal:
    field: stationName
    operator: truthy
