_confirmRemoval: true

title:
  _label: Title
  _publish: sectionFront
  _has:
    input: static
    text: ${title}

moreContentFeed:
  _component:
    include:
      - more-content-feed

canonicalUrl:
  _publish: url
  _has:
    help: Canonical URL of an article. Set when the article publishes.

# Component properties
sectionLead:
  _component:
    include:
    - section-lead

googleAdUnderStationsModule:
  _component:
    include:
      - google-ad-manager

googleAdRightRail:
  _component:
    include:
      - google-ad-manager

_groups:
  settings:
    fields:
      - title
      - canonicalUrl
