_description: |
  A list of one or more related stories

title:
  _label: Title
  _has:
    input: text
    validate:
      required: true
      max: 28

items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      required: true
      max: 3
    props:
      -
        prop: url
        _label: URL
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: overrideTitle
        _label: Headline Override
        _has:
          input: text
          validate:
            max: 80
      -
        prop: ignoreValidation
        _label: Bypass URL Validation?
        _has:
          input: checkbox
          help: Use this field if the destination of the URL entered is not a Clay page. If checked, Headline and/or Image override must be set manually.
      -
        prop: urlIsValid
        _has:
          validate:
            required: true

_groups:
  relatedItems:
    fields:
      - items
    _placeholder:
      ifEmpty: 'items.url'
      height: 100px
      text: Related Story(s)
