_version: 2.0
_description: |
  A dynamically created page containing a list of articles by tag.

_confirmRemoval: true

tag:
  _label: tag
  _publish: tag
  _has:
    input: text

content:
  _label: Topic Content
  _placeholder:
    text: Topic Content
    height: 600px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - html-embed
      - brightcove
      - omny
      - verizon-media
      - latest-videos
      - podcast-list

twoColumnComponent:
  _component:
    include:
      - two-column-component

sectionFront:
  _label: Section Front
  _publish: sectionFront
  _has:
    input: select
    search: true
    list: primary-section-fronts

_groups:
  settings:
    fields:
      - stationName
      - tag
      - sectionFront
    _placeholder:
      ifEmpty: tag
      height: 100px
      text: Tag Page

stationName:
  _label: Station Name
  _has: static
  _reveal:
    field: stationName
    operator: truthy
