_confirmRemoval: true

headline:
  _label: Headline
  _placeholder:
    height: 40px
    text: Headline
    required: true
  _has:
    input: inline
    buttons:
      - italic
      - strike
    validate:
      required: true
    help: Appears as page title

content:
  _label: Page Content
  _placeholder:
    text: Page Content
    height: 600px
  _componentList:
    fuzzy: true # allows interactives, etc to add one-off components
    include:
      - image
      - html-embed
      - subheader
      - paragraph

pageTitle:
  _publish: pageTitle
  _has:
    help: Plaintext page title, set by headline.

slug:
  _label: Slug
  _has:
    input: text
    attachedButton:
      name: magic-button
      component: static-page
      transform: getComponentInstance
      url: $SITE_PREFIX
      property: pageTitle
      moreMagic:
        - transform: toSlug
      tooltip: Generate from pageTitle

plaintextPrimaryHeadline:
  _publish:
    - ogTitle
    - pageListTitle
  _has:
    help: Plaintext title set by headline.

_groups:
  settings:
    fields:
      - stationName
      - slug

stationName:
  _label: Station Name
  _has: static
  _reveal:
    field: stationName
    operator: truthy

