_description: |
  This is the station header under the main header. It displays the station logo, top level navigational links, navigational drawers, listen button and listen drawer.
_confirmRemoval: true

stationLogo:
  _label: Station Logo Image
  _help: Upload image to override default station image
  _has:
    input: advanced-image-upload
    webLabel: Insert Image via Web
    webHelp: Supply a valid HTTPS url to an image file then click "done" button
    uploadLabel: Upload Image Attachment
    uploadHelp: Choose an image file from your computer
    validate:
      required: false

primaryLinks:
  _label: Station Primary Nav
  _placeholder:
    text: Links
    height: 100
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: Primary nav item URL
        _has:
          input: text
          type: url
          validate:
            required:
              field: secondaryLinks
              operator: length-equals
              value: 0
      -
        prop: drawer
        _label: Does this nav item have a drawer/tray/dropdown menu?
        _has:
          input: checkbox
          validate:
            required: true
      -
        prop: text
        _label: Primary nav item text
        _has:
          input: text
          enforceMaxlength: true
          validate:
            required: true
            max: 13
            maxMessage: This field must be 13 or fewer characters long
      -
        prop: secondaryLinks
        _label: Station Drawer Nav -- Secondary Links
        _reveal:
          field: drawer
          operator: truthy
        _has:
          input: complex-list
          validate:
            required:
              field: drawer
              operator: truthy
          props:
            -
              prop: text
              _label: Drawer nav item text
              _has:
                input: text
                enforceMaxlength: true
                validate:
                  required: true
                  max: 25
                  maxMessage: This field must be 25 or fewer characters long
            -
              prop: url
              _label: Drawer nav item URL
              _has:
                input: text
                type: url
                validate:
                  required: true
            
_groups:
  settings:
    fields:
      - stationLogo
      - primaryLinks
