_version: 1.0
_description: |
  This is the station header under the main header. It displays the station logo, top level navigational links, navigational drawers, listen button and listen drawer.

_confirmRemoval: true
_permission:
  update: station-navigation

stationLogo:
  _label: Station Logo Image
  _help: Upload image to override default station image
  _has:
    input: advanced-image-upload
    webLabel: Insert Image via Web
    webHelp: Supply a valid HTTPS url to an image file then click "done" button
    uploadLabel: Upload Image Attachment for Station Logo
    uploadHelp: Choose an image file from your computer for station logo to override station default logo
    validate:
      required: false

primaryLinks:
  _label: Station Primary Nav
  _placeholder:
    text: Links
    height: 100
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: Primary nav item URL
        _has:
          input: text
          type: url
          validate:
            required:
              field: drawer
              operator: falsy
            pattern: ^(https?:\/\/(www\.)?[\w-@:%.+~#=]{2,}\.[a-z]{2,}|\/)([\w-@:%+.~#?&//=]*)$
            patternMessage: e.g. http://domain.com/path or /path
      -
        prop: drawer
        _label: Does this nav item have a drawer/tray/dropdown menu?
        _has:
          input: checkbox
          validate:
            required: true
      -
        prop: text
        _label: Primary nav item text
        _has:
          input: text
          enforceMaxlength: true
          validate:
            required: true
            max: 20
            maxMessage: This field must be 20 or fewer characters long
      -
        prop: secondaryLinks
        _label: Station Drawer Nav -- Secondary Links
        _reveal:
          field: drawer
          operator: truthy
        _has:
          input: complex-list
          validate:
            required: false
          props:
            -
              prop: text
              _label: Drawer nav item text
              _has:
                input: text
                enforceMaxlength: true
                validate:
                  required: true
            -
              prop: url
              _label: Drawer nav item URL
              _has:
                input: text
                type: url
                validate:
                  required: true
                  pattern: ^(https?:\/\/(www\.)?[\w-@:%.+~#=]{2,}\.[a-z]{2,}|\/)([\w-@:%+.~#?&//=]*)$
                  patternMessage: e.g. http://domain.com/path or /path

featuredLinks:
  _label: Featured Links in Listen Nav Drawer (Up to 2)
  _placeholder:
    text: Featured Links
    height: 100
  _publish: featuredLinks
  _has:
    help: Featured links
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 2
    props:
      -
        prop: type
        _label: Featured piece page type
        _has:
          input: select
          options:
            - content
            - audio
            - contest
            - event
          validate:
            required: true
      -
        prop: URL
        _label: Featured audio/contest/events URL
        _reveal:
          field: type
          operator: '!=='
          value: content
        _has:
          input: text
          type: url
          validate:
            required:
              field: type
              operator: '!=='
              value: content
            pattern: ^(https?:\/\/(www\.)?[\w-@:%.+~#=]{2,}\.[a-z]{2,}|\/)([\w-@:%+.~#?&//=]*)$
            patternMessage: e.g. http://domain.com/path or /path
      -
        prop: contentURL
        _label: Featured content URL search
        _reveal:
          field: type
          operator: ===
          value: content
        _has:
          input: content-search
          validate:
            required:
              field: type
              operator: ===
              value: content
            pattern: ^(https?:\/\/(www\.)?[\w-@:%.+~#=]{2,}\.[a-z]{2,}|\/)([\w-@:%+.~#?&//=]*)$
            patternMessage: e.g. http://domain.com/path or /path
      -
        prop: headline
        _label: Featured piece headline
        _has:
          input: text
          validate:
            required: true
      -
        prop: image
        _label: Featured piece thumbnail
        _help: Upload image for content thumbnail
        _has:
          input: advanced-image-upload
          webLabel: Insert Image via Web
          webHelp: Supply a valid HTTPS url to an image file then click "done" button
          uploadLabel: Upload Image Attachment for Content Thumbnail
          uploadHelp: Choose an image file from your computer for content thumbnail
          validate:
            required: true

hidePodcastsLink:
  _publish: hidePodcastsLink
  _label: HIDE PODCAST LINK
  _has: checkbox

podcastsUrl:
  _publish: listenNavPodcastUrl
  _label: Enter a custom Podcast link URL here
  _reveal:
    field: hidePodcastsLink
    operator: ===
    value: false
  _has:
    input: text
    type: url
    help: If no custom URL is set, Podcast link will default to /audio

listenNav:
  _component:
    include:
      - station-listen-nav

CtaOptions:
  _has:
    input: radio
    options:
      -
        name: No CTA
        value: none
      -
        name: Newsletter Sign Up Link
        value: newsletter
      -
        name: Contact Info
        value: contact
    help: Which CTA would you like to show?

CtaNewsletterUrl:
  _label: CTA Newsletter URL
  _has:
    input: text
    type: url
  _reveal:
    field: CtaOptions
    operator: ===
    values:
      - newsletter

CtaContactInfoTelephone:
  _label: CTA Contact Telephone Number
  _has:
    input: text
    type: tel
  _reveal:
    field: CtaOptions
    operator: ===
    values:
      - contact

CtaContactInfoTelephoneDisplay:
  _label: CTA Contact Telephone Display
  _has:
    input: text
    type: text
    help: The phone number displayed to the user
  _reveal:
    field: CtaOptions
    operator: ===
    values:
      - contact

CtaContactInfoSms:
  _label: CTA Contact SMS
  _has:
    input: text
    type: tel
  _reveal:
    field: CtaOptions
    operator: ===
    values:
      - contact

CtaContactInfoSmsDisplay:
  _label: CTA Contact Text Display
  _has:
    input: text
    type: text
    help: The SMS number displayed to the user
  _reveal:
    field: CtaOptions
    operator: ===
    values:
      - contact

_groups:
  CtaContactInfoSettings:
    fields:
      - CtaContactInfoTelephone
      - CtaContactInfoSms
  settings:
    fields:
      - stationLogo (Main Nav & Drawer)
      - primaryLinks (Main Nav & Drawer)
      - hidePodcastsLink (Listen Nav Drawer)
      - podcastsUrl (Listen Nav Drawer)
      - featuredLinks (Listen Nav Drawer)
      - CtaOptions (Connect CTA Drawer)
      - CtaNewsletterUrl (Connect CTA Drawer)
      - CtaContactInfoTelephone (Connect CTA Drawer)
      - CtaContactInfoTelephoneDisplay (Connect CTA Drawer)
      - CtaContactInfoSms (Connect CTA Drawer)
      - CtaContactInfoSmsDisplay (Connect CTA Drawer)
