_description: |
  This is the station header under the main header. It displays the station logo, top level navigational links, navigational drawers, listen button and listen drawer.
_confirmRemoval: true

primaryLinks:
  _label: Station Primary Nav
  _placeholder:
    text: Links
    height: 100
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: Primary nav item URL
        _has:
          input: text
          type: url
          validate:
            required: false
      -
        prop: drawer
        _label: Does this nav item have a drawer/tray/dropdown menu?
        _has:
          input: checkbox
          validate:
            required: true
      -
        prop: text
        _label: Primary nav item text
        _has:
          input: text
          enforceMaxlength: true
          validate:
            required: true
            max: 13
            maxMessage: This field must be 13 or fewer characters long
      -
        prop: secondaryLinks
        _label: Station Drawer Nav -- Secondary Links
        _has:
          input: complex-list
          validate:
            required: false
          props:
            -
              prop: text
              _label: Drawer nav item text
              _has:
                input: text
                enforceMaxlength: true
                validate:
                  required: true
                  max: 25
                  maxMessage: This field must be 25 or fewer characters long
            -
              prop: url
              _label: Drawer nav item URL
              _has:
                input: text
                type: url
                validate:
                  required: true
            
_groups:
  settings:
    fields:
      - primaryLinks
