_description: |
  Adds `<title>`, `twitter:title`, and `og:title` tags to the head.

routeParam:
  _label: Route Param
  _has:
    input: text
    help: Define the route param whose value used for the title

suffix:
  _label: Suffix
  _has:
    input: text
    help: Add text that should appear after the dynamic route parameter

_groups:
  settings:
    fields:
      - routeParam
      - suffix
