_description: |
  Verizon Media video embed

videoId:
  _label: Video ID
  _has:
    input: text
    type: text
    validate:
      required: true

showTitle:
  _label: Show video title?
  _has: checkbox

_groups:
  video:
    _label: Verizon Media Video
    _placeholder:
      text: Verizon Media Video
      height: 30px;
      ifEmpty: videoId
    fields:
      - videoId
      - showTitle
