ingress:
  hostedZones:
    - cms.radio-stg.com
  staticDomains:
  # using stg-clay-k8s for now, to run alongside existing staging. this will be switched out.
    - stg-clay-k8s.radio-stg.com
  # update to this when ready to cut over
  #  - stg-clay.radio-stg.com
  # verify the healthCheckDomain before cutting over
  healthCheckDomain: "stg-clay-k8s.radio.com"
configmap:
  data:
    APPLE_NEWS_ENABLED: "true"
    APPLE_NEWS_PREVIEW_ONLY: "true"
    ARTICLE_AD_INSERT_EVERY: "3"
    AWS_S3_BUCKET: "radioimg-stg"
    AWS_S3_CDN_HOST: "stg-images.radio.com"
    BRIGHTCOVE_ACCOUNT_ID: "5757251889001"
    CLAY_BUS_HOST: "redis://stg-redis.radio-stg.com:6379"
    CLAY_LOG_PRETTY: "true"
    CLAY_PROVIDER: "google"
    CLAY_SCHEDULING_ENABLED: "true"
    CLAY_SITE_HOST: "stg-clay-k8s.radio.com"
    CLAY_SITE_NAME: "Clay Demo"
    CLAY_SITE_PORT: "443"
    CLAY_SITE_PROTOCOL: "https"
    CLAY_SITE_SHORTKEY: "cd"
    CLAY_STORAGE_POSTGRES_CACHE_HASH: "mydb:h"
    CLAY_STORAGE_POSTGRES_CACHE_HOST: "redis://stg-redis.radio-stg.com:6379"
    CLAY_STORAGE_POSTGRES_DB: "cms"
    CLAY_STORAGE_POSTGRES_HOST: "cmsdb-write.radio-stg.com"
    COGNITO_CONSUMER_DOMAIN: "https://etm.auth.us-east-1.amazoncognito.com"
    COGNITO_CONSUMER_REGION: "us-east-1"
    COGNITO_SERVER: "https://admin.auth.us-east-1.amazoncognito.com"
    COMPACT_BUILD: "1"
    DOUBLECLICK_BANNER_TAG: "ENT.TEST"
    ELASTIC_HOST: "http://es.radio-stg.com:9200"
    EMBEDLY_ENDPOINT: "NEED_TO_FILL_IN"
    ENABLE_GZIP: "true"
    FACEBOOK_CALLBACK_URL: "https://radio.auth.us-east-1.amazoncognito.com/oauth2/token"
    GOOGLE_AD_REFRESH_INTERVAL: "60000"
    GOOGLE_OVERRIDES_PERMISSIONS: "true"
    GOOGLE_PROFILE_URL: "https://www.googleapis.com/oauth2/v3/userinfo"
    IMPORT_CONTENT_URL: "https://hhv5vwmbg9.execute-api.us-east-1.amazonaws.com/stg/import-content"
    INLINE_EDIT_SCRIPTS: "true"
    INLINE_EDIT_STYLES: "true"
    IP_ADDRESS: "0.0.0.0"
    LOG: "info"
    PORT: "3001"
    REDIS_HASH: "mydb:h"
    REDIS_HOST: "redis://stg-redis.radio-stg.com:6379"
    REDIS_SESSION_HOST: "redis://redis-user.radio-stg.com:6379"
    SECTION_FRONTS: "music,news,sports"
    STATIC_ASSET_MAX_AGE: "0"
    URPS_AUTHORIZATIONS_URL: "https://admin-api-stg.radio-sbx.com/urps"
    URPS_HAS_AUTH_LAYER: "false"
    WEB_PLAYER_HOST: "https://assets.radio.com/webplayer"
    USE_URPS_CORE_ID: "true"
clayconfig:
  data:
    .clayconfig: |
      [keys]
        demo = accesskey
      [urls]
        demosite = http://stg-clay-k8s.radio.com
