primaryStoryLabel:
  _label: Primary Lede Label
  _has:
    input: text
    validate:
      max: 80
    help: Label for the top lede story. Eg. 'Exclusive'
items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    props:
      -
        prop: url
        _label: URL
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: overrideTitle
        _label: Headline Override
        _has:
          input: text
          validate:
            max: 80
      -
        prop: urlIsValid
        _has:
          validate:
            required: true
sectionFront:
  _label: Filter by Section Front
  _subscribe: sectionFront
  _has:
    input: static
    text: ${sectionFront}
tag:
  _label: Filter by Tag
  _subscribe: tag
  _has:
    input: static
    text: ${tag}

# Component properties
googleAdRightRail:
  _component:
    include:
    - google-ad-manager

_groups:
  settings:
    fields:
    - primaryStoryLabel
    - items
    _placeholder:
      ifEmpty: sectionFront
      height: 400px
      text: Lead Story(s)
