items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    props:
    -
      prop: url
      _label: URL
      _has:
        input: text
        type: url
        validate:
          required: true
    -
      prop: overrideTitle
      _label: Headline Override
      _has:
        input: text
        validate:
          max: 80
    -
      prop: urlIsValid
      _has:
        validate:
          required: true
sectionTitle:
  _label: Section Title
  _subscribe: sectiontitle
  _has:
    input: static
    text: ${sectionTitle}

_groups:
  settings:
    fields:
    - items
    - sectionTitle
    _placeholder:
      ifEmpty: sectionTitle
      height: 100px
      text: Lead Story(s)

# Component properties
googleAdRightRail:
  _component:
    include:
    - google-ad-manager
