_version: 5.0
primaryStoryLabel:
  _label: Primary Lede Label
  _has:
    input: text
    validate:
      max: 80
    help: Label for the top lede story. Eg. 'Exclusive'

contentType:
  _label: Content type
  _has:
    validate:
      required: true
    input: checkbox-group
    options:
      - article
      - gallery
items:
  _label: Items
  _has:
    input: complex-list
    enforceMaxlength: true
    validate:
      max: 3
    props:
      -
        prop: url
        _label: URL
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: overrideTitle
        _label: Headline Override
        _has:
          input: text
          validate:
            max: 80
      -
        prop: urlIsValid
        _has:
          validate:
            required: true

filterTags:
  _label: Exclude Tags
  _has:
    input: simple-list
    autocomplete:
      list: tags
      allowRemove: true
      allowCreate: true
    help: Exclude content from all tags

filterSecondarySectionFronts:
  _label: Exclude Secondary Section Fronts
  _has:
    input: checkbox-group
    options:
    - Pop
    - Alternative
    - Country
    -
      name: Hip-Hop R&B
      value: Hip-Hop R&B
    - Rock
    - Icons
    - Entertainment News
    - Movies
    - Television
    - National News
    - Politics
    - Local Politics
    - Small Business Pulse
    - NFL
    - MLB
    - NBA
    - NHL
    - NCAA Football
    - NCAA Basketball
    -
      name: MMA & WWE
      value: MMA & WWE

sectionFront:
  _label: Filter by Section Front
  _subscribe: sectionFront
  _has:
    input: static
    text: ${sectionFront}
tag:
  _label: Filter by Tag
  _subscribe: tag
  _has:
    input: static
    text: ${tag}

# Component properties
googleAdRightRail:
  _component:
    include:
    - google-ad-manager

_groups:
  settings:
    fields:
    - primaryStoryLabel
    - contentType
    - items
    - sectionFront
    - filterTags
    - filterSecondarySectionFronts
    _placeholder:
      ifEmpty: sectionFront
      height: 400px
      text: Lead Story(s)
