_description: |
  A simple ${type.toLowerCase()} component.

text:
  _placeholder:
    height: 50px
    text: New ${type}
    required: true
  _has:
    input: inline
    type: multi-component
    pseudoBullet: true
    buttons:
      - bold
      - italic
      - strike
      - link
    paste:
        -
          match: (https?://twitter\.com/\w+?/status/\d+)\/?
          matchLink: true
          component: tweet
          field: url
        -
          match: (https?://www\.facebook\.com/.+?/posts/\d+)
          matchLink: true
          component: facebook-post
          field: url
        -
          match: (https?://omny\.fm/shows/[^\s]+)
          matchLink: true
          component: omny
          field: clipURL
        -
          match: <h[1-9]>(.*?)</h[1-9]>
          component: subheader
          field: text
        -
          match: '[~\-_]{1,10}\s?([\w\s]+?)\s?[~\-_]{1,10}'
          component: divider
          field: title
        -
          match: <blockquote>(.*?)</blockquote>
          component: blockquote
          field: text
        -
          match: (.*)
          component: paragraph
          field: text
