_description: |
  A header for the tag page that may contain an image.

_confirmRemoval: true

tag:
  _label: tag
  _has:
    input: text
    validate:
      required: true
  _placeholder:
    height: 500px
    text: Tag Header Title
    required: true

image:
  _label: Image URL
  _placeholder:
    height: 250px
    text: Tag Header Image
    required: true
  _has:
    input: text
    type: url
    help: Must be a image url
    attachedButton:
      - name: magic-button
        component: image
        transform: getComponentInstance
        url: $SITE_PREFIX
        property: url
        tooltip: get the first image

_groups:
  settings:
    fields:
      - tag
      - image
    _placeholder:
      height: 250px
      text: Tag Header
      ifEmpty: tag
