_description: |
  List of stats widgets.

content:
  _label: Widgets component
  _placeholder:
    text: Widgets component
  _componentList:
    fuzzy: false
    include:
      - instagram-post
      - youtube

title:
  _label: Component's Title
  _has:
    validate:
      required: false
      min: 4
      max: 80
    help: The title displayed on the component's view
    input: text

titleVisible:
  _label: Show Component's Title
  _has:
    input: checkbox
    help: Show or hide the title displayed on the component's view
  
_groups:
  settings:
    _label: Component's Title
    fields:
      - title
      - titleVisible

