_description:
  Two column component

column1:
  _label: Column One
  _placeholder:
    text: Column One
    height: 600px
  _componentList:
    fuzzy: false # allows interactives, etc to add one-off components
    include:
      - image
      - instagram-post
      - brightcove
      - brightcove-live
      - youtube
      - html-embed
      - omny
      - verizon-media
      - more-content-feed
    validate:
      required: true

column2:
  _label: Column Two
  _placeholder:
    text: Column Two
    height: 600px
  _componentList:
    fuzzy: false # allows interactives, etc to add one-off components
    include:
      - image
      - instagram-post
      - brightcove
      - brightcove-live
      - youtube
      - html-embed
      - omny
      - verizon-media
      - more-content-feed
    validate:
      required: true