_description: |
  Dynamic station detail page


recentlyPlayedComponent:
  _component:
    include:
      - station-recently-played

scheduleComponent:
  _component:
    include:
      - station-schedule

discoverComponent:
  _component:
    include:
      - station-discover
