_description: |
  A header for the topic page that may contain an image.

_confirmRemoval: true

tag:
  _label: Page Title
  _has:
    input: text
    validate:
      required: true

image:
  _label: Image URL
  _has:
    input: advanced-image-upload
    webLabel: Insert Image via Web
    webHelp: Supply a valid HTTPS url to an image file then click "done" button
    uploadLabel: Upload Image Attachment
    uploadHelp: Choose an image file from your computer

_groups:
  settings:
    fields:
      - tag
      - image
    _placeholder:
      height: 250px
      text: Tag Header
      ifEmpty: tag
