_description:
  Contains a custom feed of a specified index

index:
  _label: Index
  _has:
    input: select
    options:
      -
        name: Published Articles
        value: published-articles
      -
        name: Original Videos
        value: original-videos-all
    validate:
      required: true
      requiredMessage: Please select an index
    help: Content type of the feed

size:
  _label: Size of the query
  _has:
    input: text
    validate:
      required: true
    help: Amount of entries in the feed

query:
  _label: Query
  _has:
    input: codemirror
    mode: text/x-yaml
    help: Custom elastic query for this feed written in YAML

source:
  _label: Source
  _has:
    input: simple-list

adIndex:
  _label: Ad index
  _has:
    input: text
    validate:
      required: true
    help: Number of entries before the feed ad

entries:
  _has:
    help: List of entries

_groups:
  settings:
    fields:
      - index
      - query
      - source
      - size
      - adIndex
      - entries
    _placeholder:
      text: Generic feed
      height: 100px
      ifEmpty: entries
