# Properties
curatedEvents:
  _label: Add Event
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: URL
        _has:
          input: content-search
          validate:
            required: true
  _placeholder:
    text: Add Event
    height: 200px
    required: true

events:
  _publish: events

lede:
  _publish: lede

ledeUrl:
  _label: Events Lede URL
  _has:
    input: content-search
    validate:
      required: true

moreContent:
  _publish: moreContent

pageDescription:
  _publish: pageDescription
  _has:
    input: text
    help: Plaintext description for search engines
    validate:
      required: true

pageLength:
  _label: Page Size
  _has:
    help: Number of events to load when "load more" is clicked
    input: text
    type: number

# Component
eventsList:
  _component:
    include:
      - events-list

# Groups
_groups:
  settings:
    _placeholder:
      text: Events Listing
      height: 20px
      ifEmpty: ledeUrl OR pageDescription
    fields:
      - ledeUrl
      - pageDescription
      - curatedEvents
      - pageLength
