_description: Events listing page

lede:
  _publish: lede

ledeUrl:
  _label: Events Lede URL
  _has:
    input: content-search
    validate:
      required: true

pageDescription:
  _publish: pageDescription
  _has:
    input: text
    help: Plaintext description for search engines
    validate:
      required: true

# Component
eventsList:
  _component:
    include:
      - events-list

# Groups
_groups:
  settings:
    _placeholder:
      text: Events Listing Page Settings
      height: 60px
      ifEmpty: ledeUrl OR pageDescription
    fields:
      - ledeUrl
      - pageDescription
