_version: 1.0

_description: |
  Embeds a gif via the gif's Giphy URL.

  * Only allows gifs from Giphy's API to be added.
  * Automatically defaults to responsive embed.

url:
  _label: Giphy URL
  _display: inline
  _placeholder:
    height: 50px;
    text: Giphy Embed
  _has:
    - label
    - required
    -
      fn: description
      value: Paste the URL to your gif from the Giphy website.
    -
      fn: text
      placeholder: e.g. https://giphy.com/gifs/snuggle-eIB62CqZsJL4k


# non-user-editable fields, set by model.js
giphyUrlValid:
  help: Used to decide whether or not to display the gif in the template
  _placeholder:
    text: Invalid Giphy url ${url}. This gif will not display.
    permanent: true
