_description: |
  Adds `<meta name="description">` to the head.

  This component lives in the head of the page, and is usually edited via the article component.

defaultDescription:
  _subscribe: pageDescription

description:
  _label: Description
  _has:
    input: default-text-with-override
    defaultField: defaultDescription
    permissionToOverride:
      update: meta-tags
    validate:
      required: true
    help: >-
      Description of the content on this page, used by search engines. For
      articles, this is the seo description or teaser.

_groups:
  settings:
    _label: Meta Desciption
    fields:
      - description
